package eu.the5zig.mod.server.timolia;

public enum ArcadeGame
{
  CABLES,  RUBIKSCUBE,  COLORCLOCK,  ICETRAIL,  WIZARD,  CUBEBUILDER,  BRIDGE,  QUIZ,  DNA,  TOWER,  BRIDGING,  DJ,  COLLECTOR,  ONEVSONE,  ANVIL,  CLICKER,  YOUTUBER,  GRAVITY,  ELECTRICITY,  INVISIBLESTEPS;
  
  private ArcadeGame() {}
}
